---
title: "euro22"
author: "pedusal"
date: "10 7 2022"
output: html_document
---

```{r setup, include=FALSE}

#rm(list=ls())  # REMOVE ALL OBJECTS
### Asenna hyvaksi havaitut paketit ######
# pkgs <- c("data.table", # used for data import
#           "car",        # used for testing linear hypothesis
#           "haven",      # used for data import
#           #"tidyverse",  # data manipulation etc
#           "broom",      # for working with model coefficients and model summaries efficiently
#           "lubridate",  # used for creating timestamps
#           "DT",         # for displaying data_frames nicely
#           "GGally",     # for "ggpairs" plot
#           "ggfortify",
#           "plotly")  # for enhancing plots
# 
# install.packages(c(pkgs))
# loaded_pkgs <- lapply(c(pkgs), library, character.only = TRUE)
# 
# library(readxl)

#Sys.which("make")

#install.packages("https://cran.r-project.org/src/contrib/Archive/rlang/rlang_1.0.2.tar.gz", repos = NULL, type="source")

##install.packages("gt")
##library(gt)
# library(dplyr)
```




```{r aloitus, include=FALSE}
####### Aseta tyoskentely kansio ja lataa veikkauset ###########

#Get the working directory:
#getwd()
library(readxl)
library(dplyr)
library(knitr)
#Setup the working directory:
setwd("C:/Users/Pedu/Documents/GitHub/euro22/data")
myFiles <- list.files(pattern = "xlsx$")
veikkaukset <- lapply(myFiles, function(x) read_excel(x))
```



```{r alustetaan muuttujia, include=FALSE}
################### Hae oikea rivi ################

oikearivi <- read_excel("data/11oikearivi.xlsx")

###### Muokkaaa  sopivaksi #############

oikearivi <- oikearivi %>%   
  filter(!is.na(oikearivi[,4])
                 )

### luo pelit vector
pelit <- c(1:length(oikearivi$...3)+2)
pelit[1] <- c("Nimi")
pelit[2] <- c("Yhteensa")

pelit_juoksevanro <- c(1:length(pelit))

### pelit vektoriin pelien nimet #####
for (i in pelit_juoksevanro) {
  pelit[i+2] <- c(paste(oikearivi$...3[i], "-", oikearivi$...5[i]))
}


#### luodaan pelaajat vektori #####
pelaajat <- c(1:(length(veikkaukset)))

pelaajat[1] <- c("Tulokset")

for (u in 2:length(pelaajat)) {
  veikkaus <- data.frame(veikkaukset[u]) 
  pelaajat[u] <- veikkaus[[1,5]]
  #pelaaja <- veikkaus[[1,5]]
}
```


```{r df idea, include=FALSE}
####### Tee jokaisesta vaikkauksesta oma dataframe ###########

```




```{r luodaan df:iä, include=FALSE}

################# luo veikkaustaulu
veikkaustaulu <- matrix(NA,length(pelaajat),length(pelit))
colnames(veikkaustaulu) <- c(pelit)
veikkaustaulu <- as.data.frame(veikkaustaulu)

# df = dataframe
# old.var.name = The name you don't like anymore
# new.var.name = The name you want to get

names(veikkaustaulu)[names(veikkaustaulu) == 'Yhteensa'] <- '____'


##### lisataan pelaajat veikkaustauluun #######
veikkaustaulu$Nimi <- pelaajat


################# Luo Pistetaulu ###################

pistetaulu <- matrix(NA,length(pelaajat)-1,length(pelit))
colnames(pistetaulu) <- c(pelit)
pistetaulu <- as.data.frame(pistetaulu)

```

```{r aloitus moi, echo=FALSE}
## Sano moi
print("Hello Euro22")
```
Sivun alaosasta löydät osallistujien veikkaukset sekä ehkä joku päivä jonkinlaisen koosteen niistä


```{r veikkaustaulu, echo=FALSE}
library(formattable)
library(dplyr)
#library(knitr)

## tulokset veikkaustauluun ###
  veikkaus <- data.frame(veikkaukset[1])
  
  veikkaus <- veikkaus %>%   
  filter(!is.na(veikkaus[,6])
                  )
  
for (iii in 1:length(veikkaus$...2)) {
  
    veikkaustaulu[1,2+iii] <-    c(paste(as.character(veikkaus$...6[iii]),"-",as.character(veikkaus$...8[iii])))
}
  
#### Lisataan veikkaukset veikkaustauluun

## haetaan yksittainen veikkaus kasittelyyn

for (uu in 2:(length(veikkaukset))) {
  veikkaus <- data.frame(veikkaukset[uu])
  
  veikkaus <- veikkaus %>%   
  filter(!is.na(veikkaus[,6])
                  )
  ## lisataan veikkaajan rivi veikkaustauluun
  for (iii in 1:length(veikkaus$...2)) {
  
    veikkaustaulu[uu,2+iii] <-    c(paste(as.character(veikkaus$...6[iii]),"-",as.character(veikkaus$...8[iii])))
  
    
  }
}

formattable(veikkaustaulu)

```

```{r maalintekijät, echo=FALSE}
library(formattable)
library(dplyr)


maalintekijat <- matrix(NA,length(pelaajat)-1,6)
colnames(maalintekijat) <- c("nimi", "Maalintekija1", "Maalintekija2", "Maalintekija3", "Maalintekija4", "Maalintekija5")
maalintekijat <- as.data.frame(maalintekijat)

for (uu in 2:length(veikkaukset)) {
  veikkaus <- data.frame(veikkaukset[uu])
  
  maalintekijat[uu-1,1] <- veikkaus[[1,5]]
  
  veikkaus <- veikkaus %>%   
  filter(!is.na(veikkaus[,10])
  )
         
  maalintekijat[uu-1,2:6] <- c(veikkaus$...10[2:6])
}


formattable(maalintekijat)

```



```{r tarkitus, include=FALSE}
library(dplyr)
library(knitr)
 

############ Aseta tarkistussarjat ##################

pelatut_pelit_lkm <- oikearivi %>%   
  filter(!is.na(oikearivi[,6])
                 )



koti <- oikearivi$...6 
vieras <- oikearivi$...8
koti <- as.numeric(koti)

merkki <- c(1:length(pelatut_pelit_lkm$...2))
merkki[1:length(koti)] <- NA

x <- c(1:length(pelatut_pelit_lkm$...2))
for (i in x) {
  if (koti[i]>vieras[i]){
    merkki[i] <- 1
  } else if (koti[i] == vieras[i]) {
    merkki[i] <- 2
  } else if (koti[i]<vieras[i]) {
    merkki[i] <- 3
  }
}



################### Veikkausten tarkistus ja lisays pistetauluun #######

y <- c(2:length(veikkaukset))


for (u in y) {
  tarkistettava <- data.frame(veikkaukset[u])
  pistetaulu[u-1, 1] <- tarkistettava[1,5]  ## asetetaan veikkaajan nimi
  
  tarkistettava <- tarkistettava %>% 
    filter(!is.na(...6),
         !is.na(...8)
  )
  
  koti1 <- tarkistettava$...6
  vieras1 <- tarkistettava$...8
  koti1 <- as.numeric(koti1)

  merkki1 <- c(1:length(koti1))
  merkki1[1:length(koti1)] <- NA
  
  x <- c(1:length(pelatut_pelit_lkm$...2))

  for (i in x) {

    if(koti1[i]>vieras1[i]){
      merkki1[i] <- 1

      } else if (koti1[i] == vieras1[i]) {
  
        merkki1[i] <- 2

      } else if (koti1[i]<vieras1[i]) {
  
        merkki1[i] <- 3

      }
    }

  x <- c(1:length(pelatut_pelit_lkm$...2))
  for (i in x) {
    if(koti[i] == koti1[i] & vieras[i] == vieras1[i]) {
       pistetaulu[u-1, i+2] <- c(5)
       } else if (merkki[i] == merkki1[i] 
             & (koti[i] == koti1[i] | vieras[i] == vieras1[i])){
          pistetaulu[u-1, i+2] <- c(3)
       } else if (merkki[i] == merkki1[i]) {
          pistetaulu[u-1, i+2] <- c(2)
       } else {
          pistetaulu[u-1, i+2] <- c(0)
       }
  }
  

}





pistetaulu$Yhteensa <- apply(pistetaulu[1:6,1:length(pelatut_pelit_lkm$...2)+2], 1, sum)
sort(pistetaulu$Yhteensa)


# #wb <- createWorkbook(type = "xlsx")
# library(xlsx)
# write.xlsx(mydata, "c:/mydata.xlsx")
# 
# taulu <- matrix(NA,10,50)
# y <- c(2:10)
# x <- c(1:50)
# 
# for (u in y) {
#   
#   for (i in x) {
#     taulu[u,i] <- u
#   }
# }

```




```{r pisteet printtaus, echo=FALSE}
#install.packages("formattable")
library(formattable)




myForm <- function(x) {
              formatter('span',
                        style = x ~ style(
                          color = ifelse(x > 0, "blue",
                                         ifelse(x < 0, red, "white"))
                        ))
}

formattable(pistetaulu, 
              list(Yhteensa = color_tile("white", "green"),
              lapply(pistetaulu[,3:5], myForm)
              )
            )

```

```{r pisteet printtaus testeja, eval=FALSE, include=FALSE}

formattable(pistetaulu,
            list(
              Yhteensa = color_tile("white", "blue")
              #pistetaulu[,3:length(pistetaulu[1,])] = color_tile("white", "red")
              )
            )


formattable(pistetaulu,
            lapply(pistetaulu[,3:5], formatter("span", style = x ~ ifelse(x == "A",
    style(color = "green", font.weight = "bold"), NA)))
            )


p <- data.frame(
  id = c(1, 2, 3, 4, 5),
  name = c("A1", "A2", "B1", "B2", "C1"),
  balance = accounting(c(52500, 36150, 25000, 18300, 7600), format = "d"),
  growth = percent(c(0.3, 0.3, 0.1, 0.15, 0.15), format = "d"),
  ready = formattable(c(TRUE, TRUE, FALSE, FALSE, TRUE), "yes", "no"))
p


formattable(p

, list(
  age = color_tile("white", "orange"),
  grade = formatter("span", style = x ~ ifelse(x == "A",
    style(color = "green", font.weight = "bold"), NA)),
  area(col = c(test1_score, test2_score)) ~ normalize_bar("pink", 0.2),
  final_score = formatter("span",
    style = x ~ style(color = ifelse(rank(-x) <= 3, "green", "gray")),
    x ~ sprintf("%.2f (rank: %02d)", x, rank(-x))),
  registered = formatter("span",
    style = x ~ style(color = ifelse(x, "green", "red")),
    x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
))

```